In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/kaggle/input/cardataset/data.csv")

In [3]:
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [5]:
df['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()
df['Make_encoded'] = le.fit_transform(df['Make'])

In [8]:
subset_df = df[['Make','Make_encoded']].drop_duplicates()

In [9]:
print(subset_df)

                Make  Make_encoded
0                BMW             4
17              Audi             3
32              FIAT            12
35     Mercedes-Benz            31
64          Chrysler            10
87            Nissan            33
104            Volvo            47
112            Mazda            29
194       Mitsubishi            32
294          Ferrari            13
474       Alfa Romeo             1
479           Toyota            45
604          McLaren            30
611          Maybach            28
674          Pontiac            36
736          Porsche            37
800             Saab            39
1137             GMC            15
1171         Hyundai            19
1189        Plymouth            35
1192           Honda            18
1287      Oldsmobile            34
1300          Suzuki            43
1331            Ford            14
1367        Cadillac             8
1426             Kia            21
1452         Bentley             5
1476       Chevrolet             9
1610           Dodge            11
1620     Lamborghini            22
1650         Lincoln            25
1747          Subaru            42
1792      Volkswagen            46
2116          Spyker            41
2341           Buick             7
2696           Acura             0
2921     Rolls-Royce            38
3030        Maserati            27
3173           Lexus            24
3520    Aston Martin             2
3551      Land Rover            23
3912           Lotus            26
4269        Infiniti            20
4893           Scion            40
5202         Genesis            16
5692          HUMMER            17
6921           Tesla            44
11362        Bugatti             6

In [10]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP,Make_encoded
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135,4
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650,4
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350,4
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450,4
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500,4

In [11]:
df['highway MPG']=df['highway MPG'].astype(int)

In [12]:
df.dropna(subset=['Engine HP'], inplace=True)

In [13]:
df['Engine HP']=df['Engine HP'].astype(int)

In [14]:
df.dropna(subset=['Engine Fuel Type'], inplace=True)

In [15]:
df['Engine Fuel Type'].unique()

array(['premium unleaded (required)', 'regular unleaded',
       'premium unleaded (recommended)', 'flex-fuel (unleaded/E85)',
       'diesel', 'flex-fuel (premium unleaded recommended/E85)',
       'electric', 'natural gas',
       'flex-fuel (premium unleaded required/E85)'], dtype=object)

In [16]:
le = LabelEncoder()
df['Engine Fuel Type_encoded'] = le.fit_transform(df['Engine Fuel Type'])

In [17]:
subset_df = df[['Engine Fuel Type','Engine Fuel Type_encoded']].drop_duplicates()
print(subset_df)

                                  Engine Fuel Type  Engine Fuel Type_encoded
0                      premium unleaded (required)                         7
17                                regular unleaded                         8
32                  premium unleaded (recommended)                         6
64                        flex-fuel (unleaded/E85)                         4
135                                         diesel                         0
804   flex-fuel (premium unleaded recommended/E85)                         2
1680                                      electric                         1
2556                                   natural gas                         5
2850     flex-fuel (premium unleaded required/E85)                         3

In [18]:
df['Transmission Type'].unique()

array(['MANUAL', 'AUTOMATIC', 'AUTOMATED_MANUAL', 'UNKNOWN',
       'DIRECT_DRIVE'], dtype=object)

In [19]:
df['Transmission Type']=df['Transmission Type'].replace({'MANUAL':0, 'AUTOMATIC':1,'AUTOMATED_MANUAL':2, 'DIRECT_DRIVE':3, 'UNKNOWN':4})

'MANUAL':0, 'AUTOMATIC':1,'AUTOMATED_MANUAL':2, 'DIRECT_DRIVE':3, 'UNKNOWN':4

In [20]:
df['Driven_Wheels'].unique()

array(['rear wheel drive', 'front wheel drive', 'all wheel drive',
       'four wheel drive'], dtype=object)

In [21]:
df['Driven_Wheels']=df['Driven_Wheels'].replace({'rear wheel drive':0, 'front wheel drive':1,'all wheel drive':2, 'four wheel drive':3})

'rear wheel drive':0, 'front wheel drive':1,'all wheel drive':2, 'four wheel drive':3

In [22]:
print(df['Number of Doors'].unique())

[ 2.  4.  3. nan]

In [23]:
df.dropna(subset=['Number of Doors'], inplace=True)

In [24]:
print(df['Number of Doors'].unique())

[2. 4. 3.]

In [25]:
df['Number of Doors']=df['Number of Doors'].astype(int)

In [26]:
df['Engine Cylinders'].unique()

array([ 6.,  4.,  5.,  8., 12.,  0., nan, 10.,  3., 16.])

In [27]:
df.dropna(subset=['Engine Cylinders'], inplace=True)

In [28]:
df['Engine Cylinders']=df['Engine Cylinders'].astype(int)

In [29]:
df['Vehicle Size'].unique()

array(['Compact', 'Midsize', 'Large'], dtype=object)

In [30]:
df['Vehicle Size']=df['Vehicle Size'].replace({'Compact':0, 'Midsize':1,'Large':2})

'Compact':0, 'Midsize':1,'Large':2

In [31]:
x = df[['Make_encoded', 'Engine Fuel Type_encoded', 'Transmission Type', 'Driven_Wheels', 'Number of Doors', 'Engine Cylinders', 'Vehicle Size', 'highway MPG','Engine HP']]

In [32]:
x

,Make_encoded,Engine Fuel Type_encoded,Transmission Type,Driven_Wheels,Number of Doors,Engine Cylinders,Vehicle Size,highway MPG,Engine HP
0,4,7,0,0,2,6,0,26,335
1,4,7,0,0,2,6,0,28,300
2,4,7,0,0,2,6,0,28,300
3,4,7,0,0,2,6,0,28,230
4,4,7,0,0,2,6,0,28,230
...,...,...,...,...,...,...,...,...,...
11909,0,7,1,2,4,6,1,23,300
11910,0,7,1,2,4,6,1,23,300
11911,0,7,1,2,4,6,1,23,300
11912,0,6,1,2,4,6,1,23,300
11913,25,8,1,1,4,6,1,26,221

In [33]:
y = df[['MSRP']]

In [34]:
y

        MSRP
0      46135
1      40650
2      36350
3      29450
4      34500
...      ...
11909  46120
11910  56670
11911  50620
11912  50920
11913  28995

[11812 rows x 1 columns]

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state = 0)

In [36]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestRegressor()

In [37]:
y_pred = model.predict(x_test)
from sklearn.metrics import r2_score
r2_score = r2_score(y_test,y_pred)
print("r2_score", r2_score*100)

r2_score 91.31793808546401

In [38]:
Make_encoded = int(input("enter the car's Brand"))
Engine_Fuel_Type_encoded = int(input("enter the Fuel type of the Car"))
Transmission_Type = int(input("enter the Transmission Type of the Car"))
Driven_Wheels = int(input("enter the drive wheel type"))
Number_of_Doors = int(input("enter the Number of Doors"))
Engine_Cylinders = int(input("enter the No. of Engine Cylinders"))
Vehicle_Size = int(input("enter Vehicle Size"))
highway_MPG = int(input("enter highway MPG"))
Engine_HP = int(input("enter Engine HP"))
Price_of_the_Car = [[Make_encoded,Engine_Fuel_Type_encoded,Transmission_Type,Driven_Wheels,Number_of_Doors,Engine_Cylinders,Vehicle_Size, highway_MPG,Engine_HP]]
result = model.predict(Price_of_the_Car)
print("Price_of_the_Car:",result)

enter the car's Brand 47
enter the Fuel type of the Car 8
enter the Transmission Type of the Car 1
enter the drive wheel type 2
enter the Number of Doors 4
enter the No. of Engine Cylinders 6
enter Vehicle Size 13
enter highway MPG 3300
enter Engine HP 45

Price_of_the_Car: [12260.66948232]

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"